name: Deploy to Render
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Render
        # You will use a Deploy Hook URL provided by Render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}